#include "model_pack.h"

#include <cmath>
#include <fstream>
#include <string>
#include <vector>

#include <fmt/format.h>
#include <nlohmann/json.hpp>

namespace hgps::tools {
namespace {

using nlohmann::json;

void write(const std::filesystem::path &path, const std::string &contents) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream stream{path, std::ios::binary | std::ios::trunc};
    if (!stream) {
        throw std::runtime_error(fmt::format("could not write {}", path.string()));
    }
    stream << contents;
}

/// The expected mean of each factor at an age: a smooth curve, so the calibration has something
/// age-shaped to aim at.
double expected_energy(int age) { return 1500.0 + 900.0 * (1.0 - std::exp(-0.09 * age)); }
double expected_bmi(int age) { return 15.0 + 11.0 * (1.0 - std::exp(-0.07 * age)); }

std::string factors_mean_csv(const FixturePackSpec &spec, bool male) {
    const double sex_scale = male ? 1.0 : 0.94;

    std::string out = "age,Energy,BMI\n";
    for (int age = 0; age <= spec.max_age; ++age) {
        out += fmt::format("{},{:.6f},{:.6f}\n", age, expected_energy(age) * sex_scale,
                           expected_bmi(age) * sex_scale);
    }
    return out;
}

std::string dataset_csv(const FixturePackSpec &spec) {
    // A small survey-like microdata file. It does not drive the simulation — the cohort comes
    // from the demographic data — but the config declares it and it must be consistent with the
    // factors' ranges.
    std::string out = "Gender,Age,Energy,BMI\n";
    for (int age = 0; age <= spec.max_age; ++age) {
        for (int gender = 1; gender <= 2; ++gender) {
            const double scale = gender == 1 ? 1.0 : 0.94;
            out += fmt::format("{},{},{:.4f},{:.4f}\n", gender, age,
                               expected_energy(age) * scale, expected_bmi(age) * scale);
        }
    }
    return out;
}

/// A {rows, cols, data} matrix as the HLM level definitions carry them.
json matrix(const std::vector<double> &values, std::size_t columns) {
    return json{{"rows", values.size() / columns}, {"cols", columns}, {"data", values}};
}

json coefficient(double value) {
    return json{{"value", value}, {"stdError", 0.0}, {"tValue", 0.0}, {"pValue", 0.0}};
}

std::string static_model_json(const FixturePackSpec &spec) {
    // The residual distribution is an empirical sample the model draws a row from. A handful of
    // fixed rows exercises the sampling and keeps the pack reproducible.
    const std::vector<double> energy_residuals{-120.0, -40.0, 0.0, 45.0, 130.0};
    const std::vector<double> bmi_residuals{-2.5, -0.8, 0.0, 0.9, 2.6};

    const double energy_slope =
        (expected_energy(spec.max_age) - expected_energy(0)) / spec.max_age;
    const double bmi_slope = (expected_bmi(spec.max_age) - expected_bmi(0)) / spec.max_age;

    json document;
    document["$comment"] =
        "SYNTHETIC model definition. Generated by tools/gen-fixtures; see ../data/SYNTHETIC.md.";
    document["ModelName"] = "HLM";

    document["models"]["Energy"] = json{
        {"formula", "result = lm(Energy ~ Gender + Age)"},
        {"coefficients", json{{"Intercept", coefficient(expected_energy(0))},
                              {"Gender", coefficient(90.0)},
                              {"Age", coefficient(energy_slope)}}},
        {"residuals_standard_deviation", 110.0},
        {"rsquared", 0.4}};

    // BMI is at level 2, so Energy (level 1) is available to it as a predictor.
    document["models"]["BMI"] =
        json{{"formula", "result = lm(BMI ~ Gender + Age + Energy)"},
             {"coefficients",
              json{{"Intercept", coefficient(expected_bmi(0) - 0.0012 * expected_energy(0))},
                   {"Gender", coefficient(0.8)},
                   {"Age", coefficient(bmi_slope)},
                   {"Energy", coefficient(0.0012)}}},
             {"residuals_standard_deviation", 2.2},
             {"rsquared", 0.35}};

    document["levels"]["1"] = json{{"variables", json::array({"Energy"})},
                                   {"transition", matrix({1.0}, 1)},
                                   {"inverse_transition", matrix({1.0}, 1)},
                                   {"residual_distribution", matrix(energy_residuals, 1)},
                                   {"correlation", matrix({1.0}, 1)},
                                   {"variances", json::array({1.0})}};

    document["levels"]["2"] = json{{"variables", json::array({"BMI"})},
                                   {"transition", matrix({1.0}, 1)},
                                   {"inverse_transition", matrix({1.0}, 1)},
                                   {"residual_distribution", matrix(bmi_residuals, 1)},
                                   {"correlation", matrix({1.0}, 1)},
                                   {"variances", json::array({1.0})}};

    return document.dump(2) + "\n";
}

json dynamic_equation(const std::string &name, double intercept, double age_coefficient,
                      const json &extra_coefficients, double stddev) {
    json coefficients{{"Intercept", intercept}, {"Age", age_coefficient}};
    for (const auto &entry : extra_coefficients.items()) {
        coefficients[entry.key()] = entry.value();
    }

    return json{{"Name", name},
                {"Coefficients", coefficients},
                {"ResidualsStandardDeviation", stddev}};
}

std::string dynamic_model_json(const FixturePackSpec &spec) {
    json document;
    document["$comment"] =
        "SYNTHETIC model definition. Generated by tools/gen-fixtures; see ../data/SYNTHETIC.md.";
    document["ModelName"] = "EBHLM";
    document["Country"] = json{{"Code", spec.country_code},
                               {"Name", spec.country_name},
                               {"Alpha2", spec.alpha2},
                               {"Alpha3", spec.alpha3}};
    document["BoundaryPercentage"] = 0.05;
    document["Variables"] = json::array({json{{"Name", "dEnergy"}, {"Factor", "Energy"}},
                                         json{{"Name", "dBMI"}, {"Factor", "BMI"}}});

    // BMI's equation refers to this year's change in energy, which is what the delta variables
    // are for — and what makes the level order load-bearing.
    const auto band = [](double energy_intercept, double energy_age, double bmi_intercept,
                         double bmi_age) {
        return json{
            {"Male", json::array({dynamic_equation("Energy", energy_intercept, energy_age,
                                                   json::object(), 40.0),
                                  dynamic_equation("BMI", bmi_intercept, bmi_age,
                                                   json{{"dEnergy", 0.00025}}, 0.5)})},
            {"Female", json::array({dynamic_equation("Energy", energy_intercept * 0.95,
                                                     energy_age, json::object(), 38.0),
                                    dynamic_equation("BMI", bmi_intercept * 0.95, bmi_age,
                                                     json{{"dEnergy", 0.00024}}, 0.48)})}};
    };

    document["Equations"][fmt::format("0-{}", 24)] = band(6.0, -0.04, 0.09, 0.004);
    document["Equations"][fmt::format("25-{}", spec.max_age)] = band(5.5, -0.03, 0.06, 0.002);

    return document.dump(2) + "\n";
}

std::string config_json(const FixturePackSpec &spec) {
    json document;
    document["$schema"] = "https://raw.githubusercontent.com/jude/hgps/main/schemas/v2/config.json";
    document["version"] = 2;

    document["project_requirements"] = json{
        {"demographics",
         json{{"age", true}, {"gender", true}, {"region", false}, {"ethnicity", false}}},
        {"income", json{{"enabled", false},
                        {"type", "categorical"},
                        {"categories", "3"},
                        {"adjust_to_factors_mean", false},
                        {"trended", false},
                        {"income_based_csv_output", false}}},
        {"physical_activity", json{{"enabled", false},
                                   {"type", "simple"},
                                   {"adjust_to_factors_mean", false},
                                   {"trended", false}}},
        {"risk_factors", json{{"adjust_to_factors_mean", true}, {"trended", false}}},
        {"trend", json{{"enabled", false}, {"type", "null"}}},
        {"two_stage", json{{"use_logistic", false}}}};

    document["data"] = json{{"source", "../data"}};

    document["inputs"] =
        json{{"dataset", json{{"name", "Synthetic.DataFile.csv"},
                              {"format", "csv"},
                              {"delimiter", ","},
                              {"encoding", "ASCII"},
                              {"columns", json{{"Gender", "integer"},
                                               {"Age", "integer"},
                                               {"Energy", "double"},
                                               {"BMI", "double"}}}}},
             {"settings", json{{"country_code", spec.alpha3},
                               {"size_fraction", 0.005},
                               {"age_range", json::array({0, spec.max_age})}}}};

    document["modelling"] = json{
        {"ses_model",
         json{{"function_name", "normal"}, {"function_parameters", json::array({0.0, 1.0})}}},
        {"risk_factors",
         json::array({json{{"name", "Gender"}, {"level", 0}, {"range", json::array({0, 1})}},
                      json{{"name", "Age"}, {"level", 0}, {"range", json::array({0, spec.max_age})}},
                      json{{"name", "Energy"}, {"level", 1}, {"range", json::array({800, 4000})}},
                      json{{"name", "BMI"}, {"level", 2}, {"range", json::array({12, 45})}}})},
        {"risk_factor_models",
         json{{"static", "static_model.json"}, {"dynamic", "dynamic_model.json"}}},
        {"baseline_adjustments",
         json{{"format", "csv"},
              {"delimiter", ","},
              {"encoding", "ASCII"},
              {"file_names", json{{"factorsmean_male", "Synthetic.FactorsMean.Male.csv"},
                                  {"factorsmean_female", "Synthetic.FactorsMean.Female.csv"}}}}}};

    // A short horizon: enough years for the dynamic model and the journal to matter, short
    // enough that a test runs in well under a second.
    document["running"] = json{
        {"seed", 123456789},
        {"start_time", spec.first_year},
        {"stop_time", spec.first_year + 4},
        {"trial_runs", 1},
        {"diseases", json::array({"asthma", "diabetes", "breastcancer"})},
        {"interventions",
         json{{"active_type_id", nullptr},
              {"types",
               json{{"simple",
                     json{{"active_period", json{{"start_time", spec.first_year + 2},
                                                 {"finish_time", nullptr}}},
                          {"impact_type", "absolute"},
                          {"impacts", json::array({json{{"risk_factor", "BMI"},
                                                        {"impact_value", -1.0},
                                                        {"from_age", 0},
                                                        {"to_age", nullptr}}})}}}}}}}};

    document["output"] =
        json{{"comorbidities", 2}, {"folder", "results"}, {"file_name", "result.csv"}};

    return document.dump(2) + "\n";
}

} // namespace

std::size_t write_model_pack(const std::filesystem::path &output, const FixturePackSpec &spec) {
    std::size_t written = 0;
    const auto emit = [&written, &output](const std::string &relative,
                                          const std::string &contents) {
        write(output / relative, contents);
        ++written;
    };

    emit("config.json", config_json(spec));
    emit("static_model.json", static_model_json(spec));
    emit("dynamic_model.json", dynamic_model_json(spec));
    emit("Synthetic.FactorsMean.Male.csv", factors_mean_csv(spec, true));
    emit("Synthetic.FactorsMean.Female.csv", factors_mean_csv(spec, false));
    emit("Synthetic.DataFile.csv", dataset_csv(spec));

    return written;
}

} // namespace hgps::tools
