#include "model_pack.h"

#include <cmath>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <fmt/format.h>
#include <nlohmann/json.hpp>

namespace hgps::tools {
namespace {

using nlohmann::json;

void write(const std::filesystem::path &path, const std::string &contents) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream stream{path, std::ios::binary | std::ios::trunc};
    if (!stream) {
        throw std::runtime_error(fmt::format("could not write {}", path.string()));
    }
    stream << contents;
}

/// The expected mean of each factor at an age: a smooth curve, so the calibration has something
/// age-shaped to aim at.
double expected_energy(int age) { return 1500.0 + 900.0 * (1.0 - std::exp(-0.09 * age)); }
double expected_bmi(int age) { return 15.0 + 11.0 * (1.0 - std::exp(-0.07 * age)); }

/// The FactorsMean table has to cover the configured age range, which a pack may set above the
/// data's top age — the loader says so with a located error when it does not.
std::string factors_mean_csv(bool male, int top_age) {
    const double sex_scale = male ? 1.0 : 0.94;

    std::string out = "age,Energy,BMI\n";
    for (int age = 0; age <= top_age; ++age) {
        out += fmt::format("{},{:.6f},{:.6f}\n", age, expected_energy(age) * sex_scale,
                           expected_bmi(age) * sex_scale);
    }
    return out;
}

std::string dataset_csv(const FixturePackSpec &spec) {
    // A small survey-like microdata file. It does not drive the simulation — the cohort comes
    // from the demographic data — but the config declares it and it must be consistent with the
    // factors' ranges.
    std::string out = "Gender,Age,Energy,BMI\n";
    for (int age = 0; age <= spec.max_age; ++age) {
        for (int gender = 1; gender <= 2; ++gender) {
            const double scale = gender == 1 ? 1.0 : 0.94;
            out += fmt::format("{},{},{:.4f},{:.4f}\n", gender, age,
                               expected_energy(age) * scale, expected_bmi(age) * scale);
        }
    }
    return out;
}

/// A {rows, cols, data} matrix as the HLM level definitions carry them.
json matrix(const std::vector<double> &values, std::size_t columns) {
    return json{{"rows", values.size() / columns}, {"cols", columns}, {"data", values}};
}

json coefficient(double value) {
    return json{{"value", value}, {"stdError", 0.0}, {"tValue", 0.0}, {"pValue", 0.0}};
}

std::string static_model_json(const FixturePackSpec &spec) {
    // The residual distribution is an empirical sample the model draws a row from. A handful of
    // fixed rows exercises the sampling and keeps the pack reproducible.
    const std::vector<double> energy_residuals{-120.0, -40.0, 0.0, 45.0, 130.0};
    const std::vector<double> bmi_residuals{-2.5, -0.8, 0.0, 0.9, 2.6};

    const double energy_slope =
        (expected_energy(spec.max_age) - expected_energy(0)) / spec.max_age;
    const double bmi_slope = (expected_bmi(spec.max_age) - expected_bmi(0)) / spec.max_age;

    json document;
    document["$comment"] =
        "SYNTHETIC model definition. Generated by tools/gen-fixtures; see ../data/SYNTHETIC.md.";
    document["ModelName"] = "HLM";

    document["models"]["Energy"] = json{
        {"formula", "result = lm(Energy ~ Gender + Age)"},
        {"coefficients", json{{"Intercept", coefficient(expected_energy(0))},
                              {"Gender", coefficient(90.0)},
                              {"Age", coefficient(energy_slope)}}},
        {"residualsStandardDeviation", 110.0},
        {"rSquared", 0.4}};

    // BMI is at level 2, so Energy (level 1) is available to it as a predictor.
    document["models"]["BMI"] =
        json{{"formula", "result = lm(BMI ~ Gender + Age + Energy)"},
             {"coefficients",
              json{{"Intercept", coefficient(expected_bmi(0) - 0.0012 * expected_energy(0))},
                   {"Gender", coefficient(0.8)},
                   {"Age", coefficient(bmi_slope)},
                   {"Energy", coefficient(0.0012)}}},
             {"residualsStandardDeviation", 2.2},
             {"rSquared", 0.35}};

    document["levels"]["1"] = json{{"variables", json::array({"Energy"})},
                                   {"m", matrix({1.0}, 1)},
                                   {"w", matrix({1.0}, 1)},
                                   {"s", matrix(energy_residuals, 1)},
                                   {"correlation", matrix({1.0}, 1)},
                                   {"variances", json::array({1.0})}};

    document["levels"]["2"] = json{{"variables", json::array({"BMI"})},
                                   {"m", matrix({1.0}, 1)},
                                   {"w", matrix({1.0}, 1)},
                                   {"s", matrix(bmi_residuals, 1)},
                                   {"correlation", matrix({1.0}, 1)},
                                   {"variances", json::array({1.0})}};

    return document.dump(2) + "\n";
}

json dynamic_equation(const std::string &name, double intercept, double age_coefficient,
                      const json &extra_coefficients, double stddev) {
    json coefficients{{"Intercept", intercept}, {"Age", age_coefficient}};
    for (const auto &entry : extra_coefficients.items()) {
        coefficients[entry.key()] = entry.value();
    }

    return json{{"Name", name},
                {"Coefficients", coefficients},
                {"ResidualsStandardDeviation", stddev}};
}

std::string dynamic_model_json(const FixturePackSpec &spec) {
    json document;
    document["$comment"] =
        "SYNTHETIC model definition. Generated by tools/gen-fixtures; see ../data/SYNTHETIC.md.";
    document["ModelName"] = "EBHLM";
    document["Country"] = json{{"Code", spec.country_code},
                               {"Name", spec.country_name},
                               {"Alpha2", spec.alpha2},
                               {"Alpha3", spec.alpha3}};
    document["BoundaryPercentage"] = 0.05;
    document["Variables"] = json::array({json{{"Name", "dEnergy"}, {"Factor", "Energy"}},
                                         json{{"Name", "dBMI"}, {"Factor", "BMI"}}});

    // BMI's equation refers to this year's change in energy, which is what the delta variables
    // are for — and what makes the level order load-bearing.
    const auto band = [](double energy_intercept, double energy_age, double bmi_intercept,
                         double bmi_age) {
        return json{
            {"Male", json::array({dynamic_equation("Energy", energy_intercept, energy_age,
                                                   json::object(), 40.0),
                                  dynamic_equation("BMI", bmi_intercept, bmi_age,
                                                   json{{"dEnergy", 0.00025}}, 0.5)})},
            {"Female", json::array({dynamic_equation("Energy", energy_intercept * 0.95,
                                                     energy_age, json::object(), 38.0),
                                    dynamic_equation("BMI", bmi_intercept * 0.95, bmi_age,
                                                     json{{"dEnergy", 0.00024}}, 0.48)})}};
    };

    document["Equations"][fmt::format("0-{}", 24)] = band(6.0, -0.04, 0.09, 0.004);
    document["Equations"][fmt::format("25-{}", spec.max_age)] = band(5.5, -0.03, 0.06, 0.002);

    return document.dump(2) + "\n";
}

/// @brief What one model pack calls its files, and what its config asks the engine to do.
///
/// Two packs are generated from one description so that the differences between them are a list
/// rather than two copies of a config builder that could drift apart. `model_pack.h` says why the
/// second pack exists.
struct PackLayout {
    std::string static_model;
    std::string dynamic_model;
    std::string factors_mean_male;
    std::string factors_mean_female;
    std::string dataset;
    std::string output_folder;
    std::string output_file_name;
    unsigned comorbidities;
    long long seed;

    /// Years after `spec.first_year` that the run starts, and how many years it simulates.
    int start_offset;
    int years;

    /// Added to `spec.max_age` to give `inputs.settings.age_range`'s upper bound. A configured
    /// range wider than the data's is legal — `KevinHall_FINCH` ships one — and a narrower one is
    /// refused, because the cohort is drawn from the data (src/engine/build_modules.cpp).
    int top_age_offset;

    double size_fraction;
    std::vector<std::string> diseases;

    /// The `interventions.active_type_id`; empty for a baseline-only run.
    std::string active_intervention;
};

PackLayout primary_layout() {
    return PackLayout{.static_model = "static_model.json",
                      .dynamic_model = "dynamic_model.json",
                      .factors_mean_male = "Synthetic.FactorsMean.Male.csv",
                      .factors_mean_female = "Synthetic.FactorsMean.Female.csv",
                      .dataset = "Synthetic.DataFile.csv",
                      .output_folder = "results",
                      .output_file_name = "result.csv",
                      .comorbidities = 2,
                      .seed = 123456789,
                      .start_offset = 0,
                      .years = 5,
                      .top_age_offset = 0,
                      .size_fraction = 0.005,
                      .diseases = {"asthma", "diabetes", "breastcancer"},
                      .active_intervention = {}};
}

PackLayout variant_layout() {
    // Every field here differs from the primary layout, and each difference is something the code
    // could plausibly have assumed: the model files are not beside the config, the output is not
    // called result.csv and is not the same name twice, the folder is nested, there are two
    // scenarios rather than one, and the disease set is neither the whole set nor in the pack's
    // order.
    return PackLayout{.static_model = "models/static.json",
                      .dynamic_model = "models/dynamic.json",
                      .factors_mean_male = "tables/mean-male.csv",
                      .factors_mean_female = "tables/mean-female.csv",
                      .dataset = "tables/survey.csv",
                      .output_folder = "out/nested/deeper/results",
                      .output_file_name = "synthland_{TIMESTAMP}_B.csv",
                      .comorbidities = 1,
                      .seed = 987654321,
                      .start_offset = 1,
                      .years = 6,
                      .top_age_offset = 5,
                      .size_fraction = 0.004,
                      .diseases = {"breastcancer", "asthma"},
                      .active_intervention = "food_labelling"};
}

/// @brief The `food_labelling` definition the variant pack activates.
///
/// A coverage rate strictly between 0 and 1 and at least three years of policy, because that is
/// what it takes for deviation B-24 to be reachable at all: somebody has to fail one draw, pass a
/// later one, and be wrongly offered the impact again in a third.
json food_labelling_definition(const FixturePackSpec &spec) {
    return json{
        {"active_period", json{{"start_time", spec.first_year + 2}, {"finish_time", nullptr}}},
        {"impact_type", "absolute"},
        {"coverage_rates", json::array({0.3, 0.6})},
        {"coverage_cutoff_time", 20},
        {"child_cutoff_age", 18},
        {"coefficients", json::array({0.1, 0.11, 0.12, 0.13})},
        {"adjustments", json::array({json{{"risk_factor", "Energy"}, {"value", 0.25}}})},
        {"impacts", json::array({json{{"risk_factor", "BMI"},
                                      {"impact_value", -0.05},
                                      {"from_age", 5},
                                      {"to_age", nullptr}}})}};
}

std::string config_json(const FixturePackSpec &spec, const PackLayout &layout) {
    const int start_time = spec.first_year + layout.start_offset;
    const int top_age = spec.max_age + layout.top_age_offset;

    json document;
    document["$schema"] = "schemas/v2/config.json";
    document["version"] = 2;

    document["project_requirements"] = json{
        {"demographics",
         json{{"age", true}, {"gender", true}, {"region", false}, {"ethnicity", false}}},
        {"income", json{{"enabled", false},
                        {"type", "categorical"},
                        {"categories", "3"},
                        {"adjust_to_factors_mean", false},
                        {"trended", false},
                        {"income_based_csv_output", false}}},
        {"physical_activity", json{{"enabled", false},
                                   {"type", "simple"},
                                   {"adjust_to_factors_mean", false},
                                   {"trended", false}}},
        {"risk_factors", json{{"adjust_to_factors_mean", true}, {"trended", false}}},
        {"trend", json{{"enabled", false}, {"type", "null"}}},
        {"two_stage", json{{"use_logistic", false}}}};

    document["data"] = json{{"source", "../data"}};

    document["inputs"] =
        json{{"dataset", json{{"name", layout.dataset},
                              {"format", "csv"},
                              {"delimiter", ","},
                              {"encoding", "ASCII"},
                              {"columns", json{{"Gender", "integer"},
                                               {"Age", "integer"},
                                               {"Energy", "double"},
                                               {"BMI", "double"}}}}},
             {"settings", json{{"country_code", spec.alpha3},
                               {"size_fraction", layout.size_fraction},
                               {"age_range", json::array({0, top_age})}}}};

    document["modelling"] = json{
        {"ses_model",
         json{{"function_name", "normal"}, {"function_parameters", json::array({0.0, 1.0})}}},
        {"risk_factors",
         json::array({json{{"name", "Gender"}, {"level", 0}, {"range", json::array({0, 1})}},
                      json{{"name", "Age"}, {"level", 0}, {"range", json::array({0, spec.max_age})}},
                      json{{"name", "Energy"}, {"level", 1}, {"range", json::array({800, 4000})}},
                      json{{"name", "BMI"}, {"level", 2}, {"range", json::array({12, 45})}}})},
        {"risk_factor_models",
         json{{"static", layout.static_model}, {"dynamic", layout.dynamic_model}}},
        {"baseline_adjustments",
         json{{"format", "csv"},
              {"delimiter", ","},
              {"encoding", "ASCII"},
              {"file_names", json{{"factorsmean_male", layout.factors_mean_male},
                                  {"factorsmean_female", layout.factors_mean_female}}}}}};

    // The primary pack's `simple` policy, plus — for a pack that activates it — a `food_labelling`
    // one. Both packs carry every type they define validated, whether or not one is active.
    json types{{"simple",
                json{{"active_period",
                      json{{"start_time", spec.first_year + 2}, {"finish_time", nullptr}}},
                     {"impact_type", "absolute"},
                     {"impacts", json::array({json{{"risk_factor", "BMI"},
                                                   {"impact_value", -1.0},
                                                   {"from_age", 0},
                                                   {"to_age", nullptr}}})}}}};
    if (layout.active_intervention == "food_labelling") {
        types["food_labelling"] = food_labelling_definition(spec);
    }

    json active_type_id;
    if (!layout.active_intervention.empty()) {
        active_type_id = layout.active_intervention;
    }

    // A short horizon: enough years for the dynamic model and the journal to matter, short
    // enough that a test runs in well under a second.
    document["running"] =
        json{{"seed", layout.seed},
             {"start_time", start_time},
             {"stop_time", start_time + layout.years - 1},
             {"trial_runs", 1},
             {"diseases", layout.diseases},
             {"interventions",
              json{{"active_type_id", active_type_id}, {"types", std::move(types)}}}};

    document["output"] = json{{"comorbidities", layout.comorbidities},
                              {"folder", layout.output_folder},
                              {"file_name", layout.output_file_name}};

    return document.dump(2) + "\n";
}

/// @brief Writes one pack in the layout it describes. The two packs differ only in their layout.
std::size_t write_pack(const std::filesystem::path &output, const FixturePackSpec &spec,
                       const PackLayout &layout) {
    std::size_t written = 0;
    const auto emit = [&written, &output](const std::string &relative,
                                          const std::string &contents) {
        write(output / relative, contents);
        ++written;
    };

    const int top_age = spec.max_age + layout.top_age_offset;

    emit("config.json", config_json(spec, layout));
    emit(layout.static_model, static_model_json(spec));
    emit(layout.dynamic_model, dynamic_model_json(spec));
    emit(layout.factors_mean_male, factors_mean_csv(true, top_age));
    emit(layout.factors_mean_female, factors_mean_csv(false, top_age));
    emit(layout.dataset, dataset_csv(spec));

    return written;
}

} // namespace

std::size_t write_model_pack(const std::filesystem::path &output,
                             const FixturePackSpec &spec) {
    return write_pack(output, spec, primary_layout());
}

std::size_t write_variant_model_pack(const std::filesystem::path &output,
                                     const FixturePackSpec &spec) {
    return write_pack(output, spec, variant_layout());
}

} // namespace hgps::tools
