// Ported from the baseline's src/HealthGPS.Tests/Datastore.Test.cpp (suite DatastoreTest, 20
// tests). The baseline's fixture points at a real data tree, so most of its assertions are
// "greater than zero"; here the store is the synthetic pack, whose contents are known exactly, so
// several assertions are tightened to exact values. Failures become located input issues rather
// than std::runtime_error.
#include "data/store.h"

#include "support/test_paths.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <map>
#include <numeric>

namespace {

using hgps::core::DiseaseGroup;
using hgps::core::Gender;
using hgps::core::Identifier;
using hgps::data::Store;
using hgps::diag::IssueCode;
using hgps::diag::IssueReport;

class DatastoreTest : public ::testing::Test {
  protected:
    void SetUp() override {
        const auto pack = hgps::test::synthetic_data_dir();

        // Fail, do not skip. The baseline skips 35 tests when its fixture is absent and a green
        // run then proves less than it appears to (audit B-11); this pack is generated by the
        // build, so its absence is a broken build.
        ASSERT_TRUE(std::filesystem::is_directory(pack))
            << "the synthetic data pack is missing from " << pack.string()
            << "; it is generated by the build target hgps_fixtures";

        store_ = Store::open(pack, report_);
        ASSERT_TRUE(store_.has_value()) << report_.to_string();
        ASSERT_FALSE(report_.has_errors()) << report_.to_string();

        const auto found = store_->country("SYN", report_);
        ASSERT_TRUE(found.has_value()) << report_.to_string();
        country_ = *found;
    }

    static Store::TimeFilter all_years() {
        return [](unsigned int) { return true; };
    }

    IssueReport report_;
    std::optional<Store> store_;
    hgps::core::Country country_{};
};

} // namespace

TEST_F(DatastoreTest, CreateDataStore) {
    IssueReport report;
    const auto countries = store_->countries(report);
    ASSERT_TRUE(countries.has_value()) << report.to_string();
    ASSERT_EQ(1U, countries->size());
    EXPECT_EQ(900, countries->front().code);
    EXPECT_EQ("Synthland", countries->front().name);
}

TEST_F(DatastoreTest, CreateDataStoreFailsWithWrongPath) {
    for (const auto *path : {"/x/y", "/home/x/y/z", "relative/nowhere"}) {
        IssueReport report;
        EXPECT_FALSE(Store::open(path, report).has_value()) << path;
        EXPECT_TRUE(report.contains(IssueCode::data_source_invalid)) << path;
    }
}

TEST_F(DatastoreTest, MissingIndexIsALocatedIssue) {
    const auto empty = hgps::test::scratch_dir("store_no_index");

    IssueReport report;
    EXPECT_FALSE(Store::open(empty, report).has_value());
    EXPECT_TRUE(report.contains(IssueCode::file_not_found));
}

TEST_F(DatastoreTest, CountryMissingIsReported) {
    IssueReport report;
    EXPECT_FALSE(store_->country("FAKE", report).has_value());
    ASSERT_TRUE(report.contains(IssueCode::data_country_unknown));
    EXPECT_EQ("/inputs/settings/country_code", report.issues().front().location.field);
}

TEST_F(DatastoreTest, CountryIsCaseInsensitive) {
    for (const auto *code : {"sl", "SL", "syn", "SYN", "Syn"}) {
        IssueReport report;
        EXPECT_TRUE(store_->country(code, report).has_value()) << code;
        EXPECT_FALSE(report.has_errors()) << code;
    }
}

TEST_F(DatastoreTest, CountryPopulation) {
    IssueReport report;
    const auto all = store_->population(country_, all_years(), report);
    ASSERT_TRUE(all.has_value()) << report.to_string();
    ASSERT_FALSE(all->empty());

    const auto first_year = all->front().at_time;
    const auto last_year = all->back().at_time;
    const auto mid_year = std::midpoint(first_year, last_year);

    const auto filtered = store_->population(
        country_,
        [mid_year](unsigned int year) {
            return year >= static_cast<unsigned int>(mid_year - 1) &&
                   year <= static_cast<unsigned int>(mid_year + 1);
        },
        report);
    ASSERT_TRUE(filtered.has_value());

    EXPECT_GT(all->size(), filtered->size());
    EXPECT_LT(first_year, filtered->front().at_time);
    EXPECT_GT(last_year, filtered->back().at_time);

    // Every (year, age) is present exactly once, with both sexes positive, and the series is
    // ordered by (year, age) — which the analysis and demographic modules rely on.
    std::map<int, std::map<int, hgps::core::PopulationItem>> table;
    for (const auto &item : *all) {
        EXPECT_TRUE(table[item.at_time].emplace(item.with_age, item).second)
            << "duplicate row for year " << item.at_time << " age " << item.with_age;
    }

    for (int year = first_year; year <= last_year; ++year) {
        ASSERT_TRUE(table.contains(year)) << year;
        for (int age = 0; age <= 49; ++age) {
            ASSERT_TRUE(table.at(year).contains(age)) << year << " " << age;
            const auto &item = table.at(year).at(age);
            EXPECT_GT(item.males, 0.0F);
            EXPECT_GT(item.females, 0.0F);
            EXPECT_NEAR(item.total, item.males + item.females, 0.01F);
        }
    }

    EXPECT_TRUE(std::is_sorted(all->begin(), all->end()));
}

TEST_F(DatastoreTest, CountryMortality) {
    IssueReport report;
    const auto all = store_->mortality(country_, all_years(), report);
    ASSERT_TRUE(all.has_value()) << report.to_string();
    ASSERT_FALSE(all->empty());

    for (const auto &item : *all) {
        EXPECT_GT(item.males, 0.0F);
        EXPECT_GT(item.females, 0.0F);
    }

    EXPECT_TRUE(std::is_sorted(all->begin(), all->end()));
}

TEST_F(DatastoreTest, GetDiseases) {
    const auto diseases = store_->diseases();
    ASSERT_EQ(3U, diseases.size());

    // Ordered by name, which is what the module that iterates them relies on.
    EXPECT_TRUE(std::is_sorted(diseases.begin(), diseases.end(),
                               [](const auto &left, const auto &right) {
                                   return left.name < right.name;
                               }));
}

TEST_F(DatastoreTest, GetDiseaseInfoMatchesGetDiseases) {
    for (const auto &item : store_->diseases()) {
        IssueReport report;
        const auto info = store_->disease_info(item.code, report);
        ASSERT_TRUE(info.has_value()) << item.code.to_string() << ": " << report.to_string();
        EXPECT_EQ(item.code, info->code);
        EXPECT_EQ(item.name, info->name);
        EXPECT_EQ(item.group, info->group);
    }
}

TEST_F(DatastoreTest, GetDiseaseInfoMissingIsReported) {
    IssueReport report;
    EXPECT_FALSE(store_->disease_info(Identifier{"fake"}, report).has_value());
    EXPECT_TRUE(report.contains(IssueCode::data_disease_not_in_registry));
}

TEST_F(DatastoreTest, AMisspeltDiseaseCodeGetsASuggestion) {
    // The upstream `pulmonar` / `pulmonary` split is this mistake, and the baseline's whole
    // message is "Disease code: 'pulmonar' not found." (audit D-01, ADR 0012).
    IssueReport report;
    EXPECT_FALSE(store_->disease_info(Identifier{"asthm"}, report).has_value());
    ASSERT_TRUE(report.contains(IssueCode::data_disease_not_in_registry));
    EXPECT_NE(std::string::npos, report.issues().front().message.find("asthma"))
        << report.to_string();
}

TEST_F(DatastoreTest, RetrieveDiseasesTypeInInfo) {
    const auto diseases = store_->diseases();
    const auto cancers = std::count_if(diseases.begin(), diseases.end(), [](const auto &item) {
        return item.group == DiseaseGroup::cancer;
    });

    EXPECT_EQ(1, cancers);
    EXPECT_EQ(2, static_cast<int>(diseases.size()) - cancers);
}

TEST_F(DatastoreTest, RetrieveDiseaseDefinition) {
    for (const auto &item : store_->diseases()) {
        IssueReport report;
        const auto entity = store_->disease(item, country_, report);
        ASSERT_TRUE(entity.has_value()) << item.code.to_string() << ": " << report.to_string();

        EXPECT_FALSE(entity->empty());
        EXPECT_EQ(4U, entity->measures.size());
        EXPECT_EQ(item.code, entity->info.code);
        EXPECT_EQ(country_.code, entity->country.code);

        // Two sexes over 50 ages.
        EXPECT_EQ(100U, entity->items.size());

        // Ordered by (age, gender), because a std::map builds it — the baseline used an
        // unordered_map here, making the item order depend on the standard library.
        EXPECT_TRUE(std::is_sorted(entity->items.begin(), entity->items.end(),
                                   [](const auto &left, const auto &right) {
                                       return std::tie(left.with_age, left.gender) <
                                              std::tie(right.with_age, right.gender);
                                   }));
    }
}

TEST_F(DatastoreTest, RetrieveDiseaseDefinitionForAnUnknownDiseaseIsReported) {
    const auto ghost = hgps::core::DiseaseInfo{
        .group = DiseaseGroup::other, .code = Identifier{"ghost369"}, .name = "Look at the flowers."};

    IssueReport report;
    EXPECT_FALSE(store_->disease(ghost, country_, report).has_value());
    EXPECT_TRUE(report.contains(IssueCode::file_not_found));
}

TEST_F(DatastoreTest, DiseaseRelativeRiskToDisease) {
    IssueReport report;
    const auto asthma = store_->disease_info(Identifier{"asthma"}, report);
    const auto diabetes = store_->disease_info(Identifier{"diabetes"}, report);
    ASSERT_TRUE(asthma.has_value());
    ASSERT_TRUE(diabetes.has_value());

    const auto other = store_->relative_risk_to_disease(*diabetes, *asthma, report);
    ASSERT_TRUE(other.has_value()) << report.to_string();
    EXPECT_EQ(3U, other->columns.size());
    EXPECT_FALSE(other->rows.empty());

    // A disease has no relative risk table against itself.
    IssueReport self_report;
    EXPECT_FALSE(store_->relative_risk_to_disease(*diabetes, *diabetes, self_report).has_value());
    EXPECT_FALSE(self_report.has_errors()) << "an absent interaction is a warning, not an error";
    EXPECT_TRUE(self_report.contains(IssueCode::data_missing_file));
}

TEST_F(DatastoreTest, MissingDiseaseRelativeRiskToDiseaseIsAWarning) {
    IssueReport report;
    const auto diabetes = store_->disease_info(Identifier{"diabetes"}, report);
    ASSERT_TRUE(diabetes.has_value());

    const auto ghost = hgps::core::DiseaseInfo{
        .group = DiseaseGroup::other, .code = Identifier{"ghost369"}, .name = "Look at the flowers."};

    IssueReport missing;
    EXPECT_FALSE(store_->relative_risk_to_disease(*diabetes, ghost, missing).has_value());
    EXPECT_FALSE(missing.has_errors());
    EXPECT_EQ(1U, missing.warning_count());
}

TEST_F(DatastoreTest, DiseaseRelativeRiskToRiskFactor) {
    IssueReport report;
    const auto diabetes = store_->disease_info(Identifier{"diabetes"}, report);
    ASSERT_TRUE(diabetes.has_value());

    for (const auto gender : {Gender::male, Gender::female}) {
        const auto table =
            store_->relative_risk_to_risk_factor(*diabetes, gender, Identifier{"bmi"}, report);
        ASSERT_TRUE(table.has_value()) << report.to_string();

        // Age plus five value bands.
        EXPECT_EQ(6U, table->columns.size());
        EXPECT_FALSE(table->rows.empty());
        EXPECT_NE(table->rows[0][1], table->rows[0][2]);
    }

    // A factor with no table is a warning and a disabled effect, not a failure.
    IssueReport missing;
    EXPECT_FALSE(
        store_->relative_risk_to_risk_factor(*diabetes, Gender::male, Identifier{"sodium"}, missing)
            .has_value());
    EXPECT_FALSE(missing.has_errors());
    EXPECT_EQ(1U, missing.warning_count());
}

TEST_F(DatastoreTest, RetrieveAnalysisEntity) {
    IssueReport report;
    const auto entity = store_->disease_analysis(country_, report);
    ASSERT_TRUE(entity.has_value()) << report.to_string();

    EXPECT_FALSE(entity->empty());
    EXPECT_FALSE(entity->disability_weights.empty());
    EXPECT_FALSE(entity->observed_yld.empty());
    EXPECT_FALSE(entity->life_expectancy.empty());

    EXPECT_TRUE(entity->disability_weights.contains("asthma"));
    EXPECT_NEAR(0.12F, entity->disability_weights.at("asthma"), 1e-6F);
    EXPECT_TRUE(entity->observed_yld.contains(10));
    EXPECT_TRUE(entity->observed_yld.at(10).contains(Gender::male));
    // A YLD is a fraction, not a cost: the upstream file's path says cost and its rows say YLD.
    EXPECT_GE(entity->observed_yld.at(10).at(Gender::male), 0.0);
    EXPECT_LE(entity->observed_yld.at(10).at(Gender::male), 1.0);
}

TEST_F(DatastoreTest, RetrieveBirthIndicators) {
    IssueReport report;
    const auto all = store_->birth_indicators(country_, all_years(), report);
    ASSERT_TRUE(all.has_value()) << report.to_string();
    ASSERT_FALSE(all->empty());

    const auto first_year = all->front().at_time;
    const auto last_year = all->back().at_time;
    EXPECT_GT(last_year, first_year);

    const auto mid_year = std::midpoint(first_year, last_year);
    const auto filtered = store_->birth_indicators(
        country_,
        [mid_year](unsigned int year) {
            return year >= static_cast<unsigned int>(mid_year - 1) &&
                   year <= static_cast<unsigned int>(mid_year + 1);
        },
        report);

    ASSERT_TRUE(filtered.has_value());
    EXPECT_GT(all->size(), filtered->size());
    EXPECT_LT(first_year, filtered->front().at_time);
    EXPECT_GT(last_year, filtered->back().at_time);

    for (const auto &item : *all) {
        EXPECT_GT(item.number, 0.0F);
        EXPECT_GT(item.sex_ratio, 0.0F);
    }
}

TEST_F(DatastoreTest, RetrieveCancerDefinition) {
    int cancers = 0;
    for (const auto &item : store_->diseases()) {
        if (item.group != DiseaseGroup::cancer) {
            continue;
        }
        ++cancers;

        IssueReport report;
        const auto entity = store_->disease(item, country_, report);
        ASSERT_TRUE(entity.has_value()) << report.to_string();
        EXPECT_EQ(4U, entity->measures.size());
        EXPECT_FALSE(entity->items.empty());
    }

    EXPECT_EQ(1, cancers);
}

TEST_F(DatastoreTest, RetrieveCancerParameters) {
    int cancers = 0;
    for (const auto &item : store_->diseases()) {
        if (item.group != DiseaseGroup::cancer) {
            continue;
        }
        ++cancers;

        IssueReport report;
        const auto entity = store_->cancer_parameters(item, country_, report);
        ASSERT_TRUE(entity.has_value()) << report.to_string();

        EXPECT_GT(entity->at_time, 0);
        EXPECT_FALSE(entity->prevalence_distribution.empty());
        EXPECT_FALSE(entity->survival_rate.empty());
        EXPECT_FALSE(entity->death_weight.empty());
        EXPECT_FALSE(entity->empty());
    }

    EXPECT_EQ(1, cancers);
}

TEST_F(DatastoreTest, CancerParametersForANonCancerDiseaseAreReported) {
    IssueReport report;
    const auto asthma = store_->disease_info(Identifier{"asthma"}, report);
    ASSERT_TRUE(asthma.has_value());

    EXPECT_FALSE(store_->cancer_parameters(*asthma, country_, report).has_value());
    EXPECT_TRUE(report.contains(IssueCode::data_missing_file));
}

TEST_F(DatastoreTest, RetrieveLmsParameters) {
    IssueReport report;
    const auto lms = store_->lms_parameters(report);
    ASSERT_TRUE(lms.has_value()) << report.to_string();
    ASSERT_FALSE(lms->empty());

    const auto males =
        std::count_if(lms->begin(), lms->end(), [](const auto &row) {
            return row.gender == Gender::male;
        });
    const auto females =
        std::count_if(lms->begin(), lms->end(), [](const auto &row) {
            return row.gender == Gender::female;
        });

    EXPECT_GT(males, 0);
    EXPECT_EQ(males, females);
    EXPECT_EQ(lms->size(), static_cast<std::size_t>(males + females));

    for (const auto &row : *lms) {
        EXPECT_GT(row.mu, 0.0);
        EXPECT_GT(row.sigma, 0.0);
    }
}
